### PR TITLE
Make note of JS dependencies

### LINKED ISSUE #15: Commands in the setup process fail if Yarn or Brunch are missing
### Issue

Running `$ razor new myCoolApp` gives output which suggests users run `yarn` and `brunch` commands to complete set-up.

```
$ razor new myCoolApp

# [...]

# Install your javascript dependencies
$ yarn install

# Build your javascript dependencies
$ brunch build

# [...]
```

But running `yarn install` or `brunch build` on a machine that doesn't have `yarn`/`brunch` installed will lead to 😢  `-bash: brunch: command not found`. 

Let's give the users some more guidance on what to do here.

### Reproduction steps

1. on a machine w/o `brunch` or `yarn` installed
2. run `razor new myCoolApp`
3. Follow set up instructions in output. Get to `yarn` or `brunch` step:

  * expect
```$ yarn install
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 74.48s.
```
  * see:
```
$ yarn install
-bash: yarn: command not found
```

### PR DESCRIPTION
**Pull request by dylnclrk**
To resolve #15 

* Add a dependencies section to the readme
* Update the output of `razor new` to note that yarn/brunch must be installed

### CODE REVIEW

File: mix.exs [hunk 1]
```diff
@@ -5,7 +5,7 @@ defmodule Razor.Mixfile do
   
   def project do
     [app: :razor,
-     version: "0.0.1",
+     version: "0.0.2",
```
Comment (craiglyons) [inline mix.exs]: Let's keep this at `0.0.1` please, since nothing has really changes & nobody is dependent.

**Comment by dylnclrk** [comment]
invoking `mix build_dependencies` changes `razor_archives/razor` and `razor_archives/razor-0.0.1` should I run it? Or should it just wait to get bundled in to the next release?
